server.port=8888

dynamic.mcp.register.enabled=true
dynamic.mcp.register.module-id=example-project
dynamic.mcp.register.module-name=example-project
dynamic.mcp.register.module-description=this is a example project
dynamic.mcp.register.module-version=0.0.1
dynamic.mcp.register.report-configuration.address-source=fixed
dynamic.mcp.register.report-configuration.fixed-url-prefix=http://127.0.0.1:8080
dynamic.mcp.register.module-configuration.secondary.module-id=example-project-secondary
dynamic.mcp.register.module-configuration.secondary.module-name=example-project-secondary
dynamic.mcp.register.module-configuration.secondary.module-description=secondary module in the same example service
dynamic.mcp.register.module-configuration.secondary.module-version=0.0.1